apiVersion: v1
kind: ConfigMap
metadata:
  name: elast-config-json
  namespace: kube-elastalert
  labels:
    k8s-app: elastalert
data:
  config.json: |-
    {
     "appName": "elastalert-server",
     "port": 3030,
     "elastalertPath": "/opt/elastalert",
     "verbose": false,
     "es_debug": false,
     "debug": false,
     "rulesPath": {
     "relative": true,
     "path": "/rules"
    },
     "templatesPath": {
     "relative": true,
     "path": "/rule_templates"
    },
     "es_host": "<add your elasticsearch ip here>",
     "es_port": <add your elasticsearch port here>,
     "writeback_index": "elastalert_status"
    }
